FROM httpd:2.4

WORKDIR /usr/local/apache2/

COPY ./src/*.html ./htdocs/
#COPY ./src/style ./htdocs/style
#COPY ./favicon ./htdocs/favicon
#COPY ./icons ./htdocs/icons
#COPY ./httpd.conf ./conf/httpd.conf
